services:

  postgres:
    image: postgres:17

    container_name: auravision_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: auravision
      POSTGRES_USER: auravision
      POSTGRES_PASSWORD: auravision_dev

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: