"""schema inicial

Revision ID: 01a482baa05b
Revises: 
Create Date: 2026-08-11 09:29:04.055411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a482baa05b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('componente',
    sa.Column('id_componente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_componente')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_rol_fk', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_rol_fk'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('dispositivos',
    sa.Column('id_dispositivo', sa.Uuid(), nullable=False),
    sa.Column('id_usuario_fk', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('version_firmware', sa.String(length=50), nullable=False),
    sa.Column('estado_conexion', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario_fk'], ['usuarios.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_dispositivo'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('sesiones',
    sa.Column('id_sesion', sa.Uuid(), nullable=False),
    sa.Column('id_usuario_fk', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocada', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario_fk'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_index(op.f('ix_sesiones_id_usuario_fk'), 'sesiones', ['id_usuario_fk'], unique=False)
    op.create_table('configuracion',
    sa.Column('id_configuracion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dispositivo_fk', sa.Uuid(), nullable=False),
    sa.Column('volumen', sa.Integer(), nullable=False),
    sa.Column('auto_conexion', sa.Boolean(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_dispositivo_fk'], ['dispositivos.id_dispositivo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_configuracion'),
    sa.UniqueConstraint('id_dispositivo_fk')
    )
    op.create_table('deteccion',
    sa.Column('id_deteccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dispositivo_fk', sa.Uuid(), nullable=False),
    sa.Column('tipo_objeto', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('confianza', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('distancia_estimada', sa.Integer(), nullable=False),
    sa.Column('fecha_deteccion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_dispositivo_fk'], ['dispositivos.id_dispositivo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_deteccion')
    )
    op.create_table('estado_componente',
    sa.Column('id_estado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dispositivo_fk', sa.Uuid(), nullable=False),
    sa.Column('id_componente_fk', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('mensaje_error', sa.String(length=255), nullable=False),
    sa.Column('fecha_revision', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_componente_fk'], ['componente.id_componente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_dispositivo_fk'], ['dispositivos.id_dispositivo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_estado')
    )
    op.create_table('telemetria',
    sa.Column('id_telemetria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dispositivo_fk', sa.Uuid(), nullable=False),
    sa.Column('porcentaje_bateria', sa.Integer(), nullable=False),
    sa.Column('tiempo_restante', sa.Integer(), nullable=False),
    sa.Column('estado_conexion', sa.Boolean(), nullable=False),
    sa.Column('fecha_dispositivo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voltaje_bateria', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nivel_senal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_dispositivo_fk'], ['dispositivos.id_dispositivo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_telemetria')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetria')
    op.drop_table('estado_componente')
    op.drop_table('deteccion')
    op.drop_table('configuracion')
    op.drop_index(op.f('ix_sesiones_id_usuario_fk'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_table('dispositivos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('rol')
    op.drop_table('componente')
    # ### end Alembic commands ###
